dist: xenial
language: python
python:
- 3.5
- 3.6
- 3.7
- 3.8-dev
install:
- pip install pip -U
- pip install coveralls coverage wheel
- pip install -r requirements.txt
- pip install -e . --ignore-requires-python
script:
- coverage run --source sismic -m pytest tests
- cd docs && make doctest && cd ..
- cd docs/examples/microwave/ && python -m unittest && cd ../../..
after_success:
- coveralls
matrix:
  allow_failures:
  - python: 3.8-dev
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: AlexandreDecan
  password:
    secure: bMRSAt6SKefq+ERGeq49K6nuF3CQXuoTPGTlb2JhXgPhiFXd+H1IsBjSj9fvbqbNtpd9VZJ3C0ZuvqCFa07036cbnxRDEgdIpk/cNja2Si/p2ksscRHgpNNKJb9oGuheEwuAgwKYEKdKTGVHH+EF/Lj4eobFGAfD9F77W5IDdt5RNffsx3O6pW7cb6jiy/4VTMBzn3RzTc0bVL4A59XNVB2mdhqTILuNJmiHHc3oW+q3qnrMJE2PmTn5d6hWGvRJgt/95i+qUd7vDhBvj5JFZHYYc2fHw/biO985JCaK4MpxwEjuz6q0KTFw1KK1V88R+Dt8Tk76qNqc1ctbREodfekTIfDPR/G+iPO7/JHETs3zn2g8ckxvCYYJWwWUen0uvHaaXbkfUKUAFWv6v/b92vCjr5/imuBODNYF7U/OXxBkMdm8M3Kk3JojjcKvac3YTVaYndUct0/ytTcW7H+XsWdv4yvlFKHwYhQIt7Inp18W4dOPQKKkpgI3iJhWaYkfGdweUeB5MVDU5n4u5x32MFZ3FcIbXyCfOedJDjPNFGuvvu111IfB0tkwUsvoNDR6bfoOuz2Jh8lyfLEGoxrGRwDGkF8lG6/AQeOavc6O0RhDtKyDujDV/q7vwdXlZv0Q4tK/uod3oB18sk/uceaGcOhB6C+kdhrcO7n4mPgCMTA=
  on:
    branch: master
    python: 3.5
    tags: true
